name: Get Package Version Id and Delete Gradle Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name"
        default: "com.external.spring-boot-package"
        required: true
      version_name:
        description: "Version name"
        default: "1.0.0"
        required: true

jobs:
  delete-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest package version ID
        id: get_package_version_id
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/user/packages/maven/${{ github.event.inputs.package_name }}/versions")
#           Fetch the package versions using GitHub API and print
          echo $response
#          Parse the response to find the version ID for the specified version name
          parse_response=$(echo "$response" | jq --arg name "1.0.0" '.[] | select(.name == $name)')
#          version_id=$(echo "$response" | jq --arg name "1.0.0" '.[] | select(.name == $name) | .id')
#          version_name=$(echo "$parse_response" | jq '.name')
          version_id=$(echo "$parse_response" | jq '.id')
          meta_data=$(echo "$parse_response" | jq '.metadata')
          package_type=$(echo "$meta_data" | jq '.package_type')
          echo "Version ID: $version_id"
          echo "Package Type: $package_type"
          echo "version_id=$version_id" >> $GITHUB_ENV
          echo "package_type=package_type" >> $GITHUB_ENV

      - name: Print the package version ID
        run: |
          echo "Package Version ID is ${{ env.version_id }}"

      - name: Delete package using version id
        uses: actions/delete-package-versions@v5
        if: ${{ env.version_id  != '' && env.package_type != '' }}
        with:
          package-version-ids: "${{ env.version_id }}"
          package-name: com.external.spring-boot-package
          package-type: "${{ env.package_type }}"