name: Get Package Version Id and Delete Gradle Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Name'
        required: true

jobs:
  delete-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest package version ID
        id: get_package_version_id
        run: |
          # Fetch the package versions using GitHub API
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/user/packages/maven/com.external.spring-boot-package/versions")

          echo $response

          # Parse the latest version ID using jq
          version_id=$(echo "$response" | jq --arg name "${{ github.event.inputs.version }}" '.[] | select(.name == $name) | .id')

          echo "Latest Version ID: $version_id"
          echo "version_id=$version_id" >> $GITHUB_ENV

      - name: Print the package version ID
        run: |
          echo "Package Version ID is ${{ env.version_id }}"

      - name: Print value
        run: |
          echo "Input Version: ${{ github.event.inputs.version }}"
          echo "Output Version Id: ${{ env.version_id  }}" 

      - name: Delete package using version id
        uses: actions/delete-package-versions@v5
        if: ${{ env.version_id  != '' }}
        with:
          package-version-ids: "${{ env.version_id }}"
